services:
  - type: worker
    name: telegram-reminder-bot
    runtime: python
    repo: https://github.com/profit-galievich/bot.py
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
